### ISSUE TITLE
Card swipe going under the container

### ISSUE THREAD

**Issue by subhendukundu** [HeavenOSK/flutter_swipable_stack#14]
When there's a container on width `500px`, the card swipe going under the container? Probably a zindex issue?
```
Widget build(BuildContext context) {
    return Scaffold(
      appBar: _buildAppBar(),
      body: Center(
        child: Container(
          constraints: BoxConstraints(
            minWidth: 300,
            maxWidth: 500,
            maxHeight: 730,
          ),
          padding: EdgeInsets.all(10),
          child: SwipeableStack(
            controller: _controller,
            onSwipeCompleted: (index, direction) {
              print('$index, $direction');
            },
            builder: (context, index, constraints) {
              final Post post = posts[index];
              return ProfileCard(
                post: post,
              );
            },
            itemCount: posts.length,
          ),
        ),
      ),
      bottomNavigationBar: _buildBottomBar(),
    );
  }
}
```

![bug_swpe](https://user-images.githubusercontent.com/20059141/111078721-f02d2100-851c-11eb-8718-d73e39e9e40e.gif)

**Comment by HeavenOSK** [comment]
@subhendukundu 
Thanks for your message!

I think that's an issue about swipeable area 🤔 
 
In that situation, we should add sizing widget a card instead of adding to SwipableStack.
I think we should always give the SwipableStack the largest size possible.
 
<details>
<summary>Sample code</summary>
 
```dart
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: _buildAppBar(),
      body: SwipeableStack(
        controller: _controller,
        onSwipeCompleted: (index, direction) {
          print('$index, $direction');
        },
        builder: (context, index, constraints) {
          final Post post = posts[index];
          // You should add padding here.
          return Center(
            child: Container(
              constraints: BoxConstraints(
                minWidth: 300,
                maxWidth: 500,
                maxHeight: 730,
              ),
              padding: EdgeInsets.all(10),
              child: ProfileCard(
                post: post,
              ),
            ),
          );
        },
        itemCount: posts.length,
      ),
      bottomNavigationBar: _buildBottomBar(),
    );
  }
```
</details>

### Difference of swipeable area
constrained SwipableStack | constrained inner card
:-: | :-:
swipable area is small  | swipeable area is large
<img src='https://user-images.githubusercontent.com/19836917/111089902-154b7f00-8571-11eb-8717-af5e115d9516.png' width=180/> | <img src='https://user-images.githubusercontent.com/19836917/111089918-23999b00-8571-11eb-8196-ee43d5cf9d03.png' width=180/>

**Comment by subhendukundu** [comment]
Thank you! Yes, you are right, that was the fix.
But I was wondering, would it be a bad idea to keep the cards at the higher z-index?

**Comment by HeavenOSK** [comment]
@subhendukundu 
Thanks for your message.
 
Flutter doesn’t have z-index, so we should use Overlay to display card the most front.
 
Overlay affects global in App. So if we doesn’t care about it, even when user switches tab or navigate to detail page, it keeps showing.
So library user care about that, if we introduce Overlay. So I think not using overlay for SwipableStack is reasonable now.
