### ISSUE TITLE
Cards rebuilding constantly.

### ISSUE THREAD

**Issue by luke5dm** [HeavenOSK/flutter_swipable_stack#45]
Hey, looks like all cards are rebuilding all the time as the user is dragging/as builder gets called. Seems like all children in the card are getting rebuilt. Can't quite figure it out, is there some magic with keys where all children are not really rebuilding, even though their build method is being called?

**Comment by HeavenOSK** [comment]
@luke5dm 
This library provides interactive animation and it's is one of the core concept for this library. so we need to rebuild the cards constantly.
 
So in the situation that I use this library, I care not to fetch from server when the card builds.

**Comment by luke5dm** [comment]
@HeavenOSK Right but if the card has lots of widgets that's crazy resource intensive. My cards have a youtube player and like 10 other heavy widgets in them. From your work on this, is there no way to do nice swipes without rebuilding?

**Comment by HeavenOSK** [comment]
@luke5dm 
I see. I think the Swipe UI is fundamentally heavy 🤔  So we need to get creative about saving performance.
 
There is the `stackIndex` in builder's properties so that maybe you can change behavior depending on `stackIndex`. For example, if the stackIndex is non-0, the placeholder is displayed.
 
P.S
In this package, stackCount is internally set to 3 or less.
https://github.com/HeavenOSK/flutter_swipable_stack/blob/1b5be48ed17261db747f609db91d0c1ba497b932/lib/src/swipable_stack.dart#L15

**Comment by luke5dm** [comment]
@HeavenOSK Alright, I'll look into it, thanks for getting back to me. Otherwise great work on this, really fantastic widget.
